<?php
    $array[] = array('Data','Sales');
    $data = $this->getCollection();
    foreach($data as $item){
        $array[] = array($item->getDate(),round($item->getSubtotal()));
    }
    $jsonData = Mage::helper('core')->jsonEncode($array);
?>
<?php if(count($array)>1): ?>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
  google.charts.load('current', {'packages':['corechart']});
  google.charts.setOnLoadCallback(drawChart);

  function drawChart() {
    var data = google.visualization.arrayToDataTable(<?php echo $jsonData;?>);

    var options = {
      title: 'Company Performance',
      hAxis: {title: 'Date',  titleTextStyle: {color: '#333'}},
      vAxis: {minValue: 0}
    };

    var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
    chart.draw(data, options);
  }
</script>

<div id="chart_div" style="width: 100%; height: 500px;"></div>
<?php else: ?>
<p>No Data</p>
<?php endif;?>